<a href="https://colab.research.google.com/github/aftabansari009/COLAB/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

# ***creating series and dataframes from list dictionaries and sets***

In [4]:
import pandas as pd
import numpy as np
data1=[1,2.2,3,'a',5]
S1=pd.Series(data1)
S1

0      1
1    2.2
2      3
3      a
4      5
dtype: object

In [ ]:
data=[['ram',25,'lucknow'], ['rohan',20,'delhi'],['rohit',30,'bombay'],['rohan',23,'delhi']]
df=pd.DataFrame(data,columns=['name','age','city'],index=['a',2,'c',7])
df

    name  age     city
a    ram   25  lucknow
2  rohan   20    delhi
c  rohit   30   bombay
7  rohan   23    delhi

# ***accessing rows and column by using.loc function and.iloc***

In [ ]:
a=df.loc['c']
print(a)
b=df.iloc[2]
print(b)
max=df['age'].max()
min=df['age'].min()
print(min)
mean=df['age'].mean()
print(mean)

name     rohit
age         30
city    bombay
Name: c, dtype: object
name     rohit
age         30
city    bombay
Name: c, dtype: object
20
24.5

             age
count   4.000000
mean   24.500000
std     4.203173
min    20.000000
25%    22.250000
50%    24.000000
75%    26.250000
max    30.000000

# *viewing data*

In [ ]:
df.head()#top 5 rows
df.tail()#bottom 5 rows
df.head()#top 2 rows
df.tail()#bottom 2 rows
df.info()#information about the dataframe
df.describe()#statistical information about the datframe numerical column
df.shape#shape of dataframe
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   city    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes
             age
count   4.000000
mean   24.500000
std     4.203173
min    20.000000
25%    22.250000
50%    24.000000
75%    26.250000
max    30.000000

# **filter dataframe for name this is for any condition and any colomn**

```
# This is formatted as code
```

# New Section

In [ ]:
filter=df['name']=='rohan'
a=df[filter]
a

    name  age   city
2  rohan   20  delhi
7  rohan   23  delhi

In [ ]:
filter=df['age']<=26
df[filter]

    name  age     city
a    ram   25  lucknow
2  rohan   20    delhi
7  rohan   23    delhi

# *using groupby for city and age average*

In [ ]:
a=df.groupby(['name','city'])['age'].mean()
a

name   city
ram    lucknow    25.0
rohan  delhi      21.5
rohit  bombay     30.0
Name: age, dtype: float64

# **making the data frame using dictionary**

In [6]:
#sample data
data={
    'Region':['east','west','east','south','west','south'],
    'product_type':['electronics','clothing','electronics','electronics','clothing','clothing'],
    'customres_segment':['regular','premium','regular','premium','regular','premium'],
    'sales':[1000,1500,1200,2000,1800,1300],
    'quantity':[5,10,7,12,8,6]

  }
df=pd.DataFrame(data)
print(df)
#Group By multiple colomns(e.g'Region',Product,Customrs)
grouped_data=df.groupby(['Region','product_type','customres_segment'])

#apply aggregaion functions
aggregated_data=grouped_data['quantity'].sum()
print(aggregated_data)

  Region product_type customres_segment  sales  quantity
0   east  electronics           regular   1000         5
1   west     clothing           premium   1500        10
2   east  electronics           regular   1200         7
3  south  electronics           premium   2000        12
4   west     clothing           regular   1800         8
5  south     clothing           premium   1300         6
Region  product_type  customres_segment
east    electronics   regular              12
south   clothing      premium               6
        electronics   premium              12
west    clothing      premium              10
                      regular               8
Name: quantity, dtype: int64

# **making dataframe using list & dictionaries**

In [7]:
emp_name=['alice','bob','charlie','david','eve']
salary=[60000,75000,50000,90000,65000]
df=pd.DataFrame({'name':emp_name,'salary':salary})
##display the dataframe without index
print(df.to_string(index=False))

   name  salary
  alice   60000
    bob   75000
charlie   50000
  david   90000
    eve   65000